<?php

namespace SoundboardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SoundclipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoundclipRepository extends EntityRepository
{
}
